export enum ReferensiPilihanJenisKegiatanEnum {
    MENYUSUN_ANILISIS_KEKUATAN = 1,
    MENYUSUN_STRATEGI_PENGEMBANGAN = 2,
    MEMFASILITASI_PENYUSUNAN_RENCANA = 3,
    MEMFASILITASI_PENGUATAN_KAPASITAS = 4,
    MELAKUKAN_PENDAMPINGAN = 5,
    MEMFASILITASI_TERJADINYA_KOLABORASI = 6,
    MEMOBILISASI_FORUM = 7
  }
  
  export enum PengembanganKomunitasPeranEnum {
    KETUA = 1,
    PENGURUS = 2,
    PENASEHAT = 3,
    LAINNYA = 4
  }